name: Push

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx1
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.US_WEST_2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.US_WEST_2_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Fetch version number
        id: get-version
        run: echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build and push
        id: container-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: thar-be-a-beta-admin
          IMAGE_TAG: ${{ env.IMAGE_VERSION }}-${{ github.run_number }}-${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          push: true
          tags: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
