name: Push

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'Makefile'

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    environment: dev
    env:
      ECR_REPOSITORY: thar-be-a-public-beta-admin
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon Public ECR
        id: login-public-ecr
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.US_WEST_2_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.US_WEST_2_AWS_SECRET_ACCESS_KEY }}

      - name: Get version number
        id: container-ver
        run: echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get short SHA
        id: short-sha
        run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Build and push
        id: container-build
        env:
          IMAGE_TAG: ${{ env.IMAGE_VERSION }}-${{ env.SHORT_SHA }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          push: true
          tags: ${{ secrets.PUBLIC_ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
