name: Push

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
            docker_arch: amd64
          - platform: linux/arm64
            arch: arm64
            docker_arch: arm64v8
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.US_WEST_2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.US_WEST_2_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get version number
        id: container-ver
        run: echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get short SHA
        id: short-sha
        run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Build and push
        id: container-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: thar-be-a-beta-admin-${{ matrix.arch }}
          IMAGE_TAG: ${{ env.IMAGE_VERSION }}-${{ env.SHORT_SHA }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
            ARCH=${{ matrix.arch }}
            DOCKER_ARCH=${{ matrix.docker_arch }}
          push: true
          tags: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
