name: Release

on:
  release:
    types: [published]
    branches: [develop]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      PUBLIC_ECR_REPOSITORY: thar-be-a-public-beta-admin
      ECR_REPOSITORY: thar-be-a-beta-admin
    environment:
      name: ${{ matrix.environment }}
    strategy:
      matrix:
        include:
          - environment: us-east-1-prod
            aws-region: us-east-1
          - environment: us-west-2-prod
            aws-region: us-west-2
          - environment: ap-northeast-1-prod
            aws-region: ap-northeast-1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get version number
        id: container-ver
        run: echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get short SHA
        id: short-sha
        run: echo "SHORT_SHA=$(git rev-parse --short=8 ${{ github.ref }})" >> $GITHUB_ENV

      - name: Push Image to multiple registries
        id: multi-push
        env:
          IMAGE_TAG: ${{ env.IMAGE_VERSION }}-${{ env.SHORT_SHA }}
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ${{ secrets.PUBLIC_ECR_REGISTRY }}/${{ env.PUBLIC_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          dst: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
